server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh            #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**     #断言，路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          #过滤器配置
          #filters:
            #- AddRequestParameter=X-Request-Id, 1024
          #断言配置
          predicates:
            - Path=/payment/lb/**
            - After=2021-04-24T13:36:40.153+08:00[Asia/Shanghai]
            #- Before=2021-04-24T13:36:40.153+08:00[Asia/Shanghai]
            #- Between=2021-04-23T13:36:40.153+08:00[Asia/Shanghai],2021-04-25T13:36:40.153+08:00[Asia/Shanghai]
            #- Cookie=username,djx
            #- Header=X-Request-Id, \d+ #请求头有x-Request-Id属性，并且值为整数的正则表达式
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ #要有参数名username，并且值还要整数才能路由 ?username=1

eureka:
  instance:
    hostname: cloud-gateway-service

  client: #服务提供者provider注册进eureka服务列表内
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/